#!/usr/bin/env bash

#: exec_target = cli

## Build frontend (static website)
##
## Usage: fin fe/build

# Abort if anything fails
set -e

cd ${PROJECT_ROOT}/frontend

# Contents of both .cache and public have to be dropped
# Cannot use 'gatsby clean' here as it tries to drop the entry folder and we cannot do this since .cache is a mounted as a volume
rm -rf .cache/*
rm -rf public/*

time npm run build
