#!/usr/bin/env bash

#: exec_target = cli

## Initialize frontend codebase
##
## Usage: fin fe/code-init
## In case of any errors during this command execution try to stop gatsby
## container first:
## fin stop api

# Abort if anything fails
set -e

cd "$PROJECT_ROOT/frontend"

# Install dependencies
# Using "npm ci" instead of "npm install" here to avoid unintentional package-lock.json updates
time npm ci
